<p><h1>Test H1</h1>
Bulleted list:</p>
<p>
<ul>
  <li>Point 1

  </li>
  <li>Point 2

 <ul>
   <li>Sub-point 2.1
   </li>
   <li>Sub-point 2.2
   </li>
 </ul>
  </li>
  <li>Point 3

  <ol>
    <li>(numbered) Sub-point 3.1
    </li>
    <li>(numbered) Sub-point 3.2

   <ul>
     <li>Sub-point 3.2.1
     </li>
   </ul>
    </li>
    <li>(numbered) Sub-point 3.3

   <ol class='loweralpha'>
     <li>(loweralpha) Sub-point 3.3.1
     </li>
     <li>(loweralpha) Sub-point 3.3.2
     </li>
   </ol>
    </li>
    <li>Sub-point 3.4

   <ol class='upperalpha'>
     <li>(upperalpha) Sub-point 3.4.1
     </li>
     <li>(upperalpha) Sub-point 3.4.2
     </li>
</ol>
    </li>
</ol>
  </li>
</ul></p>
<p>List ended
</p>
